version: '3'

services:
  web:
    build: .
    #restart: unless-stopped
    networks:
      - ushahidiplatform-docker_default
    ports:
      - "8080:8080"
    env_file: .env

networks:
  ushahidiplatform-docker_default:
    external: true

